version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Santiago"
    commit-message:
      prefix: "[DEPENDABOT]"

